# Generated by Django 5.2.12 on 2026-05-05 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('min_points', models.PositiveIntegerField(default=0, verbose_name='Минимум баллов')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Стипендия',
                'verbose_name_plural': 'Стипендии',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название грамоты')),
                ('file', models.FileField(upload_to='certificates/', verbose_name='Файл грамоты')),
                ('event_level', models.CharField(choices=[('city', 'Городской'), ('region', 'Областной'), ('national', 'Всероссийский'), ('international', 'Международный'), ('university', 'Вузовский')], max_length=20, verbose_name='Уровень мероприятия')),
                ('place', models.CharField(choices=[('participant', 'Участник'), ('prize_winner', 'Призер'), ('winner', 'Победитель')], max_length=20, verbose_name='Место')),
                ('event_date', models.DateField(verbose_name='Дата мероприятия')),
                ('auto_points', models.PositiveIntegerField(default=0, verbose_name='Автоматические баллы')),
                ('custom_points', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ручные баллы (админ)')),
                ('extracted_text', models.TextField(blank=True, verbose_name='Распознанный текст')),
                ('status', models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Подтверждена'), ('rejected', 'Отклонена'), ('archived', 'В архиве')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Грамота',
                'verbose_name_plural': 'Грамоты',
                'ordering': ('-event_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='PointAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(verbose_name='Корректировка')),
                ('reason', models.TextField(verbose_name='Причина')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='made_adjustments', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Корректировка баллов',
                'verbose_name_plural': 'Корректировки баллов',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ScholarshipCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_points', models.IntegerField(verbose_name='Баллы за грамоты')),
                ('adjustment_points', models.IntegerField(verbose_name='Корректировка')),
                ('total_points', models.IntegerField(verbose_name='Итог')),
                ('is_eligible', models.BooleanField(verbose_name='Подходит')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to='core.scholarship')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Расчет стипендии',
                'verbose_name_plural': 'Расчеты стипендий',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_book_number', models.CharField(blank=True, max_length=30, verbose_name='Номер зачетки')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('institution', models.CharField(blank=True, max_length=255, verbose_name='Институт')),
                ('specialty', models.CharField(blank=True, max_length=255, verbose_name='Специальность')),
                ('course', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Курс')),
                ('study_form', models.CharField(blank=True, choices=[('full_time', 'Очная'), ('part_time', 'Заочная'), ('mixed', 'Очно-заочная')], max_length=20, verbose_name='Форма обучения')),
                ('portfolio', models.FileField(blank=True, null=True, upload_to='portfolios/', verbose_name='Портфолио')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль студента',
                'verbose_name_plural': 'Профили студентов',
            },
        ),
    ]
