# Generated by Django 5.2.12 on 2026-05-19 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='moderator_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий модератора'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='Причина отклонения'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_certificates', to=settings.AUTH_USER_MODEL, verbose_name='Проверил'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='status',
            field=models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Подтверждена'), ('rejected', 'Отклонена'), ('archived', 'В архиве')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('user_created', 'Создан пользователь'), ('user_updated', 'Обновлен пользователь'), ('user_deleted', 'Удален пользователь'), ('certificate_updated', 'Обновлена грамота'), ('certificate_deleted', 'Удалена грамота'), ('points_adjusted', 'Корректировка баллов'), ('status_changed', 'Изменение статуса грамоты'), ('report_exported', 'Выгружен отчет')], max_length=50, verbose_name='Действие')),
                ('details', models.TextField(blank=True, verbose_name='Детали')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
                ('certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='core.certificate')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Журнал аудита',
                'verbose_name_plural': 'Журнал аудита',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ScholarshipDeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Начало приема')),
                ('end_date', models.DateField(verbose_name='Окончание приема')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='core.scholarship')),
            ],
            options={
                'verbose_name': 'Дедлайн подачи',
                'verbose_name_plural': 'Дедлайны подачи',
                'ordering': ('end_date',),
            },
        ),
    ]
